version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend/chroma:/app/chroma
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
